### ISSUE TITLE
Update ERC creation workflow and clarify in API

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-web-api#42]
## ~~Situation~~ See comment below for alternative solution!

ERC creation roughly has these steps:

1. submit workspace (upload, or provide pointer)
2. process upload (create container, extract metadata etc.)
3. user reviews metadata
4. user clicks "save" button (and saves the metadata, which starts the brokering)

This process must be communicated clearly to the user, especially in the metadata edit form. The buttons should effectively convey the messages "Finish ERC creation" or "Abort ERC creation", so that it is clear that not doing anything in the metadata review (e.g. closing the browser) will actually not create the ERC.

@7048730 Imho this clarification of the process means that we do _not_ need brokering during the first processing (i.e. in the loader), but only need to do it during metadata update, because the metadata update will _always_ be done.

Also, step 2 might take quite a long time and therefore the upload must **support asynchronous communication**, which is crucial to integrate this into larger architectures. See also http://farazdagi.com/blog/2014/rest-long-running-jobs/ [outcome of discussion with publisher architect]

Here we have two approaches, both of which we should try out (see also [this SO answer](https://stackoverflow.com/a/5625525/261210)!

- queue + request/response (polling, easier? for us to implement)
- callback (preferable for integration in larger architectures)

## ~~Tasks~~

- [ ] API docs reflect the process by providing an intermediate "workspace" resource
  - `GET /api/v1/workspace` lists all _uncompleted_ workspaces _of the current user_, or all (including completed ones) if the user has admin level
  - `GET /api/v1/workspace/<id>` provides workspace information, most importantly status
    - property `status`
      - `processing`
      - `reviewable` > processing is completed, metadata is ready for review
      - `completed` > makes a redirect to ERC with HTTP status `303 See Other`
    - property `eta`, the estimated time to finish. Default `eta` is the average of all completed workspaces in the database
    - property `cancel` - a link where the workspace processing can be stopped (see below)
    - property `lastUpdate` - that last update time = also completion time
    - property `compendium` - if (and only if) the compendium is created
  - `DELETE /api/v1/workspace/<id>` endpoint (only admins and creating user)
    - should have two variants: really delete, or set `deleted: true` in the compendium object. The API _never_ returns deleted objects, so no need to document this. To retrieve them direct database access is needed.
  - two variants for creating a compendium
    - `POST /api/v1/compendium` immediately returns with a response, status code `HTTP 202` and a `Location` header field point to the respective workspace, see also [on Location header](https://en.wikipedia.org/wiki/HTTP_location)
    - `POST /api/v1/compendium?callback=http://callback.org/endpoint` also reply with `HTTP 202` and the `Location` header, but it would also register a callback which is called once the workspace processing is completed, see below
- [ ] implementation in loader and muncher updated
- [ ] issue for UI to implement this created
  - loader only creates workspace
  - muncher makes ERC out of workspace (this is what takes long)

### The callback

If a callback endpoint is provided on creating a new compendium, e.g. `POST /api/v1/compendium?callback=http://publisher.com/publication/100/appendix/1`, the endpoint is called with the following operation after the workspace processing is completed:

```
PUT publisher.com/publication/100/appendix/1
# content of GET /api/v1/workspace/<id>
{
  "status": "reviewable",
  "compendium": "https://o2r.uni-muenster.de/api/v1/compendium/1234",
  "lastUpdate": "2017..."
}
```

Should we also notify the endpoint if the status changes from `reviewable` to `completed`?

### Our own UI / websockets

It is currently unclear how we can _also_ provide the notification via websockets... tbc

**Comment by 7048730** [comment]
I agree, reasonable clarification concerning the brokering.

Since "deposition" is "repo speak": do we only have a deposition, once the newly created ERC intermediate resource is deposited at a 3rd party repo (i.e. status _shipped_, which means MD checked)?
I think it's the other way round, we have an intermediate deposition on our server until we ship. So I would rather not call this state "deposition" to avoid confusing in the workflow.
My suggestion would be something like "resource", "workspace", "intermediate", **"candidate"**.

**Comment by o2r-user** [comment]
I like "candidate".

**Comment by nuest** [comment]
@7048730 I updated the description above, using "workspace", because that is also the term we use explaining this process to people. Feedback welcome.

@MarkusKonk @jansule Can you please take a look at the rough API sketch above and comment here if that is understandable for you and if this works from the UI perspective?

**Comment by nuest** [comment]
I would like to propose an **alternative approach**: the `candidate` property.
Instead of having another resource, we leave everything under `/api/v1/compendium`, with the following rules:

- After the upload the compendium has a properity `candidate: true`.
- This field is updated _after the user has reviewed and saved metadata_, to `candidate: false`.
- When querying `../compendium`, only the "non-candidates" are shown publicly.
- When querying `../compendium` as a user _for a user_, all compendia, including the candidates, are shown.
- When querying `../compendium` as an editor (or higher), candidates can be shown with `?show_candidates=true`.

**Arguments in favour**:

- We use ERC vs. workspace to distinguish _what_ is loaded/uploaded into our service. It would be confusing to use that term also to denote the state of the resource (you can load a valid ERC and it becomes a workspace again?)
- No need to query two endpoints in the UI to show an author it's candidates and completed compendia.
- `DELETE` can be implemented for `../compendium/, independent of them being candidates or not (only admins and authoring user).
- This is independent of the ideas of a callback functionality (see first comment).
- The "cancel" workspace processing suggested above is probably quite complex and we're unlikely to implement it soon. Since the creation of Dockerfile and image are going to be part of a job, we should have logic to stop a job instead. Jobs already have the fields to store last update etc. We should re-use that implementation.

**Comment by 7048730** [comment]
engage

**Comment by jansule** [comment]
@nuest, leaving everything under `/api/v1/compendium` seems more reasonable to me. Therefore, I support your last suggestion.
